// <auto-generated />
using System;
using CarCatalog.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CarCatalog.Database.Migrations
{
    [DbContext(typeof(CarCatalogContext))]
    [Migration("20191226232211_InitSchema")]
    partial class InitSchema
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CarCatalog.Database.Entities.Car", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AmountDoors")
                        .HasColumnType("int");

                    b.Property<int>("AmountSeats")
                        .HasColumnType("int");

                    b.Property<Guid>("CatalogId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Color")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DriveType")
                        .HasColumnType("int");

                    b.Property<Guid>("EngineId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("GearBox")
                        .HasColumnType("int");

                    b.Property<string>("Manufacturer")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Mileage")
                        .HasColumnType("int");

                    b.Property<string>("Model")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OriginCountry")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PictureName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<string>("VIN")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CatalogId");

                    b.HasIndex("CategoryId");

                    b.HasIndex("EngineId");

                    b.ToTable("Car");

                    b.HasData(
                        new
                        {
                            Id = new Guid("fa86e173-2a42-4a1d-86bb-a021a8c576c1"),
                            AmountDoors = 5,
                            AmountSeats = 3,
                            CatalogId = new Guid("139d3f48-e507-447a-8ba5-27e03db09624"),
                            CategoryId = new Guid("c8786545-d6bd-4d84-9790-9cd67701db74"),
                            Color = "gold",
                            DriveType = 2,
                            EngineId = new Guid("1f955975-5e38-42b6-bbef-8556941863b0"),
                            GearBox = 1,
                            Manufacturer = "Honda",
                            Mileage = 166847,
                            Model = "Element",
                            OriginCountry = "Ghana",
                            PictureName = "Honda.jpg",
                            Type = 3,
                            VIN = "YK8D0EE05RJW12432"
                        },
                        new
                        {
                            Id = new Guid("e5a56b6e-f2de-4001-bc1b-d8ffd00db4fd"),
                            AmountDoors = 2,
                            AmountSeats = 2,
                            CatalogId = new Guid("6f86c1b9-1174-46d2-a369-9cbe1c0a116b"),
                            CategoryId = new Guid("c8786545-d6bd-4d84-9790-9cd67701db74"),
                            Color = "ivory",
                            DriveType = 3,
                            EngineId = new Guid("25ccffa1-b364-4726-98e9-1afd4e963e1d"),
                            GearBox = 3,
                            Manufacturer = "Tesla",
                            Mileage = 60134,
                            Model = "Golf",
                            OriginCountry = "Namibia",
                            PictureName = "Tesla.jpg",
                            Type = 2,
                            VIN = "WZG1KCNJS2H926992"
                        },
                        new
                        {
                            Id = new Guid("dba4703d-61bb-4127-b8b7-797f9cd42ba3"),
                            AmountDoors = 2,
                            AmountSeats = 4,
                            CatalogId = new Guid("6f86c1b9-1174-46d2-a369-9cbe1c0a116b"),
                            CategoryId = new Guid("c8786545-d6bd-4d84-9790-9cd67701db74"),
                            Color = "maroon",
                            DriveType = 2,
                            EngineId = new Guid("1f955975-5e38-42b6-bbef-8556941863b0"),
                            GearBox = 0,
                            Manufacturer = "Jeep",
                            Mileage = 84206,
                            Model = "F-150",
                            OriginCountry = "Guinea",
                            PictureName = "Jeep.jpg",
                            Type = 4,
                            VIN = "QMPXXZT3P3GC44044"
                        },
                        new
                        {
                            Id = new Guid("ae756af4-a6a2-4eeb-b16c-988e8e1cd4e3"),
                            AmountDoors = 4,
                            AmountSeats = 5,
                            CatalogId = new Guid("139d3f48-e507-447a-8ba5-27e03db09624"),
                            CategoryId = new Guid("df26f0ba-854c-4f43-90f6-1abeab3ff092"),
                            Color = "gold",
                            DriveType = 2,
                            EngineId = new Guid("5f6746d3-1a9c-4fc5-869a-6a5c8560fd6b"),
                            GearBox = 2,
                            Manufacturer = "Jaguar",
                            Mileage = 192680,
                            Model = "CTS",
                            OriginCountry = "Cyprus",
                            PictureName = "Jaguar.jpg",
                            Type = 3,
                            VIN = "PJAJXEQTROOP49093"
                        },
                        new
                        {
                            Id = new Guid("cb413d95-5a10-4931-8ff0-1cbe5c81f50b"),
                            AmountDoors = 4,
                            AmountSeats = 2,
                            CatalogId = new Guid("139d3f48-e507-447a-8ba5-27e03db09624"),
                            CategoryId = new Guid("df26f0ba-854c-4f43-90f6-1abeab3ff092"),
                            Color = "lime",
                            DriveType = 3,
                            EngineId = new Guid("2eed9dc3-45c9-44ea-91f7-74c74f639fc1"),
                            GearBox = 3,
                            Manufacturer = "Maserati",
                            Mileage = 174551,
                            Model = "Escalade",
                            OriginCountry = "Zambia",
                            PictureName = "Maserati.jpg",
                            Type = 3,
                            VIN = "QUBXPIBNLZQZ45103"
                        },
                        new
                        {
                            Id = new Guid("be009aca-498e-42ef-846d-8222c0b51334"),
                            AmountDoors = 4,
                            AmountSeats = 4,
                            CatalogId = new Guid("6f86c1b9-1174-46d2-a369-9cbe1c0a116b"),
                            CategoryId = new Guid("66d4775d-f4d3-4664-a69c-456cefeaefe8"),
                            Color = "cyan",
                            DriveType = 3,
                            EngineId = new Guid("2e793b29-ff25-4a23-b6fd-c04dd1cd5ad0"),
                            GearBox = 3,
                            Manufacturer = "Land Rover",
                            Mileage = 169618,
                            Model = "Charger",
                            OriginCountry = "El Salvador",
                            PictureName = "Land Rover.jpg",
                            Type = 4,
                            VIN = "WZ9ROKT6SSRJ73285"
                        },
                        new
                        {
                            Id = new Guid("f3de44d4-6daf-4777-97c7-b8292d3ad4a1"),
                            AmountDoors = 5,
                            AmountSeats = 4,
                            CatalogId = new Guid("6f86c1b9-1174-46d2-a369-9cbe1c0a116b"),
                            CategoryId = new Guid("c8786545-d6bd-4d84-9790-9cd67701db74"),
                            Color = "green",
                            DriveType = 1,
                            EngineId = new Guid("23b87e53-36ee-4bf7-814b-834b5f209037"),
                            GearBox = 3,
                            Manufacturer = "Land Rover",
                            Mileage = 170765,
                            Model = "PT Cruiser",
                            OriginCountry = "Algeria",
                            PictureName = "Land Rover.jpg",
                            Type = 1,
                            VIN = "0334BLXE7XZE94729"
                        },
                        new
                        {
                            Id = new Guid("d1e74571-4ca7-4848-a8c5-9c10ce038bdb"),
                            AmountDoors = 5,
                            AmountSeats = 2,
                            CatalogId = new Guid("139d3f48-e507-447a-8ba5-27e03db09624"),
                            CategoryId = new Guid("66d4775d-f4d3-4664-a69c-456cefeaefe8"),
                            Color = "olive",
                            DriveType = 3,
                            EngineId = new Guid("2eed9dc3-45c9-44ea-91f7-74c74f639fc1"),
                            GearBox = 2,
                            Manufacturer = "BMW",
                            Mileage = 18634,
                            Model = "Civic",
                            OriginCountry = "Slovenia",
                            PictureName = "BMW.jpg",
                            Type = 0,
                            VIN = "Q96XY2NU44D871613"
                        },
                        new
                        {
                            Id = new Guid("e9435900-4c9b-45e4-bdc9-aed7d774f1a6"),
                            AmountDoors = 3,
                            AmountSeats = 4,
                            CatalogId = new Guid("139d3f48-e507-447a-8ba5-27e03db09624"),
                            CategoryId = new Guid("66d4775d-f4d3-4664-a69c-456cefeaefe8"),
                            Color = "tan",
                            DriveType = 3,
                            EngineId = new Guid("2eed9dc3-45c9-44ea-91f7-74c74f639fc1"),
                            GearBox = 2,
                            Manufacturer = "Aston Martin",
                            Mileage = 40374,
                            Model = "Charger",
                            OriginCountry = "Holy See (Vatican City State)",
                            PictureName = "Aston Martin.jpg",
                            Type = 3,
                            VIN = "JLKSW6WXNBZC87345"
                        },
                        new
                        {
                            Id = new Guid("68b4dfb3-fd67-41b9-8bcf-88202dbf29b5"),
                            AmountDoors = 5,
                            AmountSeats = 3,
                            CatalogId = new Guid("139d3f48-e507-447a-8ba5-27e03db09624"),
                            CategoryId = new Guid("66d4775d-f4d3-4664-a69c-456cefeaefe8"),
                            Color = "silver",
                            DriveType = 2,
                            EngineId = new Guid("87c9ee10-2f12-43f2-8042-def639afa3ee"),
                            GearBox = 3,
                            Manufacturer = "Dodge",
                            Mileage = 44699,
                            Model = "Camry",
                            OriginCountry = "Barbados",
                            PictureName = "Dodge.jpg",
                            Type = 1,
                            VIN = "22N98ZT8G1BM39572"
                        },
                        new
                        {
                            Id = new Guid("01fe8ead-e6b6-4821-862b-bbb47916e682"),
                            AmountDoors = 3,
                            AmountSeats = 5,
                            CatalogId = new Guid("6f86c1b9-1174-46d2-a369-9cbe1c0a116b"),
                            CategoryId = new Guid("66d4775d-f4d3-4664-a69c-456cefeaefe8"),
                            Color = "lime",
                            DriveType = 0,
                            EngineId = new Guid("7413db33-f1f1-45c8-98a4-c116c1e57a4c"),
                            GearBox = 2,
                            Manufacturer = "Audi",
                            Mileage = 46645,
                            Model = "Colorado",
                            OriginCountry = "Cook Islands",
                            PictureName = "Audi.jpg",
                            Type = 4,
                            VIN = "LCXW1WJUXQJI74931"
                        },
                        new
                        {
                            Id = new Guid("b3f452dd-c4b2-44cb-b16c-d8c9cb445e54"),
                            AmountDoors = 4,
                            AmountSeats = 3,
                            CatalogId = new Guid("139d3f48-e507-447a-8ba5-27e03db09624"),
                            CategoryId = new Guid("c8786545-d6bd-4d84-9790-9cd67701db74"),
                            Color = "olive",
                            DriveType = 3,
                            EngineId = new Guid("cee7f524-d325-48ac-9720-3ad28098b435"),
                            GearBox = 3,
                            Manufacturer = "Toyota",
                            Mileage = 104244,
                            Model = "Golf",
                            OriginCountry = "Bahamas",
                            PictureName = "Toyota.jpg",
                            Type = 5,
                            VIN = "CL1TEM2CADV292491"
                        },
                        new
                        {
                            Id = new Guid("2cb9fc82-b79c-453c-a700-28cc10d97c12"),
                            AmountDoors = 2,
                            AmountSeats = 5,
                            CatalogId = new Guid("6f86c1b9-1174-46d2-a369-9cbe1c0a116b"),
                            CategoryId = new Guid("c8786545-d6bd-4d84-9790-9cd67701db74"),
                            Color = "ivory",
                            DriveType = 3,
                            EngineId = new Guid("053acf54-e485-4c69-b521-9a3e050c1e48"),
                            GearBox = 3,
                            Manufacturer = "Honda",
                            Mileage = 176509,
                            Model = "Expedition",
                            OriginCountry = "Congo",
                            PictureName = "Honda.jpg",
                            Type = 2,
                            VIN = "KGRK9NU5XSVL37661"
                        },
                        new
                        {
                            Id = new Guid("0576073d-3ca5-4cb7-a4b5-5debb0a8fa8f"),
                            AmountDoors = 2,
                            AmountSeats = 2,
                            CatalogId = new Guid("6f86c1b9-1174-46d2-a369-9cbe1c0a116b"),
                            CategoryId = new Guid("c8786545-d6bd-4d84-9790-9cd67701db74"),
                            Color = "purple",
                            DriveType = 3,
                            EngineId = new Guid("fbfdc6f2-4a0c-4215-aa7a-5b14d0c0d5a4"),
                            GearBox = 3,
                            Manufacturer = "Chevrolet",
                            Mileage = 40919,
                            Model = "Explorer",
                            OriginCountry = "Hungary",
                            PictureName = "Chevrolet.jpg",
                            Type = 1,
                            VIN = "ZDT2QL3NMDSG41120"
                        },
                        new
                        {
                            Id = new Guid("c59526eb-7eb5-4795-a5bc-b0edf165ac9f"),
                            AmountDoors = 5,
                            AmountSeats = 3,
                            CatalogId = new Guid("139d3f48-e507-447a-8ba5-27e03db09624"),
                            CategoryId = new Guid("df26f0ba-854c-4f43-90f6-1abeab3ff092"),
                            Color = "indigo",
                            DriveType = 1,
                            EngineId = new Guid("fbfdc6f2-4a0c-4215-aa7a-5b14d0c0d5a4"),
                            GearBox = 0,
                            Manufacturer = "Land Rover",
                            Mileage = 140379,
                            Model = "Mustang",
                            OriginCountry = "Croatia",
                            PictureName = "Land Rover.jpg",
                            Type = 4,
                            VIN = "SQ8SZAHVROGS26496"
                        },
                        new
                        {
                            Id = new Guid("85a165d7-b868-47f9-9023-26dad5a1c821"),
                            AmountDoors = 2,
                            AmountSeats = 2,
                            CatalogId = new Guid("139d3f48-e507-447a-8ba5-27e03db09624"),
                            CategoryId = new Guid("66d4775d-f4d3-4664-a69c-456cefeaefe8"),
                            Color = "yellow",
                            DriveType = 3,
                            EngineId = new Guid("053acf54-e485-4c69-b521-9a3e050c1e48"),
                            GearBox = 2,
                            Manufacturer = "BMW",
                            Mileage = 112849,
                            Model = "Grand Cherokee",
                            OriginCountry = "British Indian Ocean Territory (Chagos Archipelago)",
                            PictureName = "BMW.jpg",
                            Type = 3,
                            VIN = "QI51PMWZXWR138648"
                        },
                        new
                        {
                            Id = new Guid("0dec5f28-f4cd-4c15-b9e9-4cb526683bdd"),
                            AmountDoors = 5,
                            AmountSeats = 5,
                            CatalogId = new Guid("139d3f48-e507-447a-8ba5-27e03db09624"),
                            CategoryId = new Guid("c8786545-d6bd-4d84-9790-9cd67701db74"),
                            Color = "yellow",
                            DriveType = 0,
                            EngineId = new Guid("afe256ad-8bc7-41fd-b163-bca69c94de2f"),
                            GearBox = 0,
                            Manufacturer = "Volkswagen",
                            Mileage = 171127,
                            Model = "A8",
                            OriginCountry = "Lesotho",
                            PictureName = "Volkswagen.jpg",
                            Type = 2,
                            VIN = "VC4BN35VH6EH34685"
                        },
                        new
                        {
                            Id = new Guid("d08ce175-949c-46eb-ae98-597f90f5abcb"),
                            AmountDoors = 3,
                            AmountSeats = 5,
                            CatalogId = new Guid("139d3f48-e507-447a-8ba5-27e03db09624"),
                            CategoryId = new Guid("df26f0ba-854c-4f43-90f6-1abeab3ff092"),
                            Color = "indigo",
                            DriveType = 3,
                            EngineId = new Guid("f28e550b-6e49-4c4c-aafe-7cf2d1b66c77"),
                            GearBox = 2,
                            Manufacturer = "Maserati",
                            Mileage = 82063,
                            Model = "Camaro",
                            OriginCountry = "Peru",
                            PictureName = "Maserati.jpg",
                            Type = 1,
                            VIN = "9MQPR2PNSOQ971072"
                        },
                        new
                        {
                            Id = new Guid("ff703e03-d38a-4b5d-8808-e06c673051f4"),
                            AmountDoors = 2,
                            AmountSeats = 5,
                            CatalogId = new Guid("6f86c1b9-1174-46d2-a369-9cbe1c0a116b"),
                            CategoryId = new Guid("66d4775d-f4d3-4664-a69c-456cefeaefe8"),
                            Color = "white",
                            DriveType = 3,
                            EngineId = new Guid("1f955975-5e38-42b6-bbef-8556941863b0"),
                            GearBox = 0,
                            Manufacturer = "Aston Martin",
                            Mileage = 199513,
                            Model = "Colorado",
                            OriginCountry = "Antigua and Barbuda",
                            PictureName = "Aston Martin.jpg",
                            Type = 5,
                            VIN = "JA3C732QZDYU71904"
                        },
                        new
                        {
                            Id = new Guid("e7824811-48c9-4d8d-a208-d275b3d032ec"),
                            AmountDoors = 3,
                            AmountSeats = 5,
                            CatalogId = new Guid("139d3f48-e507-447a-8ba5-27e03db09624"),
                            CategoryId = new Guid("66d4775d-f4d3-4664-a69c-456cefeaefe8"),
                            Color = "grey",
                            DriveType = 3,
                            EngineId = new Guid("909be4e1-5bfe-463a-adce-f2462c48d8bc"),
                            GearBox = 2,
                            Manufacturer = "Kia",
                            Mileage = 111883,
                            Model = "ATS",
                            OriginCountry = "Maldives",
                            PictureName = "Kia.jpg",
                            Type = 4,
                            VIN = "L7ZLSKUBK4Q646545"
                        });
                });

            modelBuilder.Entity("CarCatalog.Database.Entities.Catalog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Catalog");

                    b.HasData(
                        new
                        {
                            Id = new Guid("139d3f48-e507-447a-8ba5-27e03db09624"),
                            CreatedDate = new DateTime(2019, 12, 26, 22, 44, 17, 829, DateTimeKind.Local).AddTicks(8390),
                            Name = "eos",
                            UserId = new Guid("e8657ca1-623b-445d-9ae1-42ae3b2bdce4")
                        },
                        new
                        {
                            Id = new Guid("6f86c1b9-1174-46d2-a369-9cbe1c0a116b"),
                            CreatedDate = new DateTime(2019, 12, 26, 15, 16, 18, 341, DateTimeKind.Local).AddTicks(414),
                            Name = "adipisci",
                            UserId = new Guid("3ab6fb24-46ea-40c8-be19-acd34b7d92cc")
                        });
                });

            modelBuilder.Entity("CarCatalog.Database.Entities.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PictureName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Category");

                    b.HasData(
                        new
                        {
                            Id = new Guid("66d4775d-f4d3-4664-a69c-456cefeaefe8"),
                            Name = "Sport",
                            PictureName = "Sport.jpg"
                        },
                        new
                        {
                            Id = new Guid("df26f0ba-854c-4f43-90f6-1abeab3ff092"),
                            Name = "Limousine",
                            PictureName = "Limousine.jpg"
                        },
                        new
                        {
                            Id = new Guid("c8786545-d6bd-4d84-9790-9cd67701db74"),
                            Name = "Passenger",
                            PictureName = "Passenger.jpg"
                        });
                });

            modelBuilder.Entity("CarCatalog.Database.Entities.Engine", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AmountCylinders")
                        .HasColumnType("int");

                    b.Property<float>("Capacity")
                        .HasColumnType("real");

                    b.Property<int>("Code")
                        .HasColumnType("int");

                    b.Property<int>("Fuel")
                        .HasColumnType("int");

                    b.Property<int>("HorsePower")
                        .HasColumnType("int");

                    b.Property<int>("KiloWat")
                        .HasColumnType("int");

                    b.Property<bool>("Turbo")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("Engine");

                    b.HasData(
                        new
                        {
                            Id = new Guid("bd26fb0f-015d-4625-9009-7af1797fc111"),
                            AmountCylinders = 3,
                            Capacity = 1f,
                            Code = 25,
                            Fuel = 0,
                            HorsePower = 95,
                            KiloWat = 70,
                            Turbo = true
                        },
                        new
                        {
                            Id = new Guid("91627a36-4129-4286-9de1-8cac97073478"),
                            AmountCylinders = 3,
                            Capacity = 1f,
                            Code = 30,
                            Fuel = 0,
                            HorsePower = 116,
                            KiloWat = 85,
                            Turbo = true
                        },
                        new
                        {
                            Id = new Guid("87c9ee10-2f12-43f2-8042-def639afa3ee"),
                            AmountCylinders = 4,
                            Capacity = 1.5f,
                            Code = 35,
                            Fuel = 0,
                            HorsePower = 150,
                            KiloWat = 110,
                            Turbo = true
                        },
                        new
                        {
                            Id = new Guid("23b87e53-36ee-4bf7-814b-834b5f209037"),
                            AmountCylinders = 4,
                            Capacity = 2f,
                            Code = 40,
                            Fuel = 0,
                            HorsePower = 200,
                            KiloWat = 147,
                            Turbo = true
                        },
                        new
                        {
                            Id = new Guid("909be4e1-5bfe-463a-adce-f2462c48d8bc"),
                            AmountCylinders = 4,
                            Capacity = 1.4f,
                            Code = 0,
                            Fuel = 0,
                            HorsePower = 204,
                            KiloWat = 150,
                            Turbo = true
                        },
                        new
                        {
                            Id = new Guid("053acf54-e485-4c69-b521-9a3e050c1e48"),
                            AmountCylinders = 4,
                            Capacity = 2f,
                            Code = 0,
                            Fuel = 0,
                            HorsePower = 300,
                            KiloWat = 221,
                            Turbo = true
                        },
                        new
                        {
                            Id = new Guid("447d8039-02a0-47a7-bab9-57d4e0cbfe11"),
                            AmountCylinders = 5,
                            Capacity = 2.5f,
                            Code = 0,
                            Fuel = 0,
                            HorsePower = 400,
                            KiloWat = 294,
                            Turbo = true
                        },
                        new
                        {
                            Id = new Guid("f28e550b-6e49-4c4c-aafe-7cf2d1b66c77"),
                            AmountCylinders = 4,
                            Capacity = 2f,
                            Code = 35,
                            Fuel = 0,
                            HorsePower = 150,
                            KiloWat = 110,
                            Turbo = true
                        },
                        new
                        {
                            Id = new Guid("2e793b29-ff25-4a23-b6fd-c04dd1cd5ad0"),
                            AmountCylinders = 4,
                            Capacity = 2f,
                            Code = 40,
                            Fuel = 0,
                            HorsePower = 190,
                            KiloWat = 140,
                            Turbo = true
                        },
                        new
                        {
                            Id = new Guid("2eed9dc3-45c9-44ea-91f7-74c74f639fc1"),
                            AmountCylinders = 4,
                            Capacity = 2f,
                            Code = 45,
                            Fuel = 0,
                            HorsePower = 245,
                            KiloWat = 180,
                            Turbo = true
                        },
                        new
                        {
                            Id = new Guid("25ccffa1-b364-4726-98e9-1afd4e963e1d"),
                            AmountCylinders = 6,
                            Capacity = 3f,
                            Code = 0,
                            Fuel = 0,
                            HorsePower = 354,
                            KiloWat = 260,
                            Turbo = true
                        },
                        new
                        {
                            Id = new Guid("afe256ad-8bc7-41fd-b163-bca69c94de2f"),
                            AmountCylinders = 6,
                            Capacity = 2.9f,
                            Code = 0,
                            Fuel = 0,
                            HorsePower = 450,
                            KiloWat = 331,
                            Turbo = true
                        },
                        new
                        {
                            Id = new Guid("1f955975-5e38-42b6-bbef-8556941863b0"),
                            AmountCylinders = 6,
                            Capacity = 3f,
                            Code = 55,
                            Fuel = 0,
                            HorsePower = 340,
                            KiloWat = 250,
                            Turbo = true
                        },
                        new
                        {
                            Id = new Guid("7413db33-f1f1-45c8-98a4-c116c1e57a4c"),
                            AmountCylinders = 4,
                            Capacity = 2f,
                            Code = 35,
                            Fuel = 1,
                            HorsePower = 150,
                            KiloWat = 110,
                            Turbo = true
                        },
                        new
                        {
                            Id = new Guid("5f6746d3-1a9c-4fc5-869a-6a5c8560fd6b"),
                            AmountCylinders = 4,
                            Capacity = 2f,
                            Code = 40,
                            Fuel = 1,
                            HorsePower = 190,
                            KiloWat = 140,
                            Turbo = true
                        },
                        new
                        {
                            Id = new Guid("5215243f-c85a-420b-8283-b504cbb0fe8f"),
                            AmountCylinders = 4,
                            Capacity = 2f,
                            Code = 40,
                            Fuel = 1,
                            HorsePower = 204,
                            KiloWat = 150,
                            Turbo = true
                        },
                        new
                        {
                            Id = new Guid("fbfdc6f2-4a0c-4215-aa7a-5b14d0c0d5a4"),
                            AmountCylinders = 6,
                            Capacity = 3f,
                            Code = 0,
                            Fuel = 1,
                            HorsePower = 347,
                            KiloWat = 255,
                            Turbo = true
                        },
                        new
                        {
                            Id = new Guid("5614a251-c9cc-4286-a808-cd0847ef2856"),
                            AmountCylinders = 6,
                            Capacity = 3f,
                            Code = 50,
                            Fuel = 1,
                            HorsePower = 286,
                            KiloWat = 210,
                            Turbo = true
                        },
                        new
                        {
                            Id = new Guid("cee7f524-d325-48ac-9720-3ad28098b435"),
                            AmountCylinders = 6,
                            Capacity = 3f,
                            Code = 45,
                            Fuel = 1,
                            HorsePower = 231,
                            KiloWat = 170,
                            Turbo = true
                        });
                });

            modelBuilder.Entity("CarCatalog.Database.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Avatar")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("User");

                    b.HasData(
                        new
                        {
                            Id = new Guid("e8657ca1-623b-445d-9ae1-42ae3b2bdce4"),
                            Avatar = "https://s3.amazonaws.com/uifaces/faces/twitter/dhrubo/128.jpg",
                            UserName = "Marie.Gutkowski"
                        },
                        new
                        {
                            Id = new Guid("3ab6fb24-46ea-40c8-be19-acd34b7d92cc"),
                            Avatar = "https://s3.amazonaws.com/uifaces/faces/twitter/Karimmove/128.jpg",
                            UserName = "Jayda88"
                        },
                        new
                        {
                            Id = new Guid("b66cb147-ab10-4f6a-ac42-f2f4374ff80d"),
                            Avatar = "https://s3.amazonaws.com/uifaces/faces/twitter/adhamdannaway/128.jpg",
                            UserName = "Amalia.Wunsch"
                        },
                        new
                        {
                            Id = new Guid("9cdf2f2e-e5e9-41a9-981c-7821519c63f6"),
                            Avatar = "https://s3.amazonaws.com/uifaces/faces/twitter/agustincruiz/128.jpg",
                            UserName = "Billy.Durgan48"
                        });
                });

            modelBuilder.Entity("CarCatalog.Database.Entities.Car", b =>
                {
                    b.HasOne("CarCatalog.Database.Entities.Catalog", "Catalog")
                        .WithMany("Cars")
                        .HasForeignKey("CatalogId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CarCatalog.Database.Entities.Category", "Category")
                        .WithMany("Cars")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CarCatalog.Database.Entities.Engine", "Engine")
                        .WithMany("Cars")
                        .HasForeignKey("EngineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CarCatalog.Database.Entities.Catalog", b =>
                {
                    b.HasOne("CarCatalog.Database.Entities.User", "User")
                        .WithMany("Catalogs")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
