// <auto-generated />
using System;
using CarCatalog.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CarCatalog.Database.Migrations
{
    [DbContext(typeof(CarCatalogContext))]
    [Migration("20191229172613_InitializeSchema")]
    partial class InitializeSchema
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CarCatalog.Database.Entities.Car", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AmountDoors")
                        .HasColumnType("int");

                    b.Property<int>("AmountSeats")
                        .HasColumnType("int");

                    b.Property<Guid?>("CatalogId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Color")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDateEntity")
                        .HasColumnType("datetime2");

                    b.Property<int>("DriveType")
                        .HasColumnType("int");

                    b.Property<Guid>("EngineId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("GearBox")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Manufacturer")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Mileage")
                        .HasColumnType("int");

                    b.Property<string>("Model")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OriginCountry")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PictureName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdateDateEntity")
                        .HasColumnType("datetime2");

                    b.Property<string>("VIN")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CatalogId");

                    b.HasIndex("CategoryId");

                    b.HasIndex("EngineId");

                    b.ToTable("Car");

                    b.HasData(
                        new
                        {
                            Id = new Guid("f7b5247b-da3e-4c1f-b031-4fdbfd523876"),
                            AmountDoors = 2,
                            AmountSeats = 2,
                            CatalogId = new Guid("924cce38-da44-4b44-a9f5-430d3830debe"),
                            CategoryId = new Guid("8411e08f-c1d9-4a7c-a3c8-5c7f956645f3"),
                            Color = "gold",
                            CreatedDateEntity = new DateTime(2019, 12, 29, 18, 26, 12, 215, DateTimeKind.Local).AddTicks(2838),
                            DriveType = 3,
                            EngineId = new Guid("4f5b62c0-5346-4745-990a-8dc0a6688d80"),
                            GearBox = 2,
                            IsDeleted = false,
                            Manufacturer = "Porsche",
                            Mileage = 175678,
                            Model = "Wrangler",
                            OriginCountry = "Botswana",
                            PictureName = "Porsche.jpg",
                            Type = 3,
                            UpdateDateEntity = new DateTime(2019, 12, 29, 18, 26, 12, 215, DateTimeKind.Local).AddTicks(2891),
                            VIN = "F9A77Y7BQBPL98981"
                        },
                        new
                        {
                            Id = new Guid("f8a5c971-db8a-41b8-8f7c-c68f9be6c390"),
                            AmountDoors = 2,
                            AmountSeats = 4,
                            CatalogId = new Guid("26c28d0b-55b8-4f7a-92c3-a775565eb7e9"),
                            CategoryId = new Guid("0c5f8f9e-a0e5-4698-87af-588da11adc6f"),
                            Color = "gold",
                            CreatedDateEntity = new DateTime(2019, 12, 29, 18, 26, 12, 225, DateTimeKind.Local).AddTicks(9468),
                            DriveType = 0,
                            EngineId = new Guid("b68f0932-74aa-4960-b84b-563c657132bd"),
                            GearBox = 2,
                            IsDeleted = false,
                            Manufacturer = "Porsche",
                            Mileage = 33305,
                            Model = "Mercielago",
                            OriginCountry = "Switzerland",
                            PictureName = "Porsche.jpg",
                            Type = 3,
                            UpdateDateEntity = new DateTime(2019, 12, 29, 18, 26, 12, 225, DateTimeKind.Local).AddTicks(9524),
                            VIN = "744H0ZSR00HV38749"
                        },
                        new
                        {
                            Id = new Guid("f3811e85-5d92-4858-b7ea-7fc0cf56aa73"),
                            AmountDoors = 4,
                            AmountSeats = 2,
                            CatalogId = new Guid("924cce38-da44-4b44-a9f5-430d3830debe"),
                            CategoryId = new Guid("8411e08f-c1d9-4a7c-a3c8-5c7f956645f3"),
                            Color = "olive",
                            CreatedDateEntity = new DateTime(2019, 12, 29, 18, 26, 12, 226, DateTimeKind.Local).AddTicks(743),
                            DriveType = 1,
                            EngineId = new Guid("527d76bd-0892-4041-8008-172319ea0f0c"),
                            GearBox = 0,
                            IsDeleted = false,
                            Manufacturer = "Hyandai",
                            Mileage = 180719,
                            Model = "Spyder",
                            OriginCountry = "Afghanistan",
                            PictureName = "Hyandai.jpg",
                            Type = 5,
                            UpdateDateEntity = new DateTime(2019, 12, 29, 18, 26, 12, 226, DateTimeKind.Local).AddTicks(755),
                            VIN = "KBJZH4DKCOC316914"
                        },
                        new
                        {
                            Id = new Guid("c2982a71-b9db-4a79-9fea-5b2b93bbc760"),
                            AmountDoors = 4,
                            AmountSeats = 4,
                            CatalogId = new Guid("26c28d0b-55b8-4f7a-92c3-a775565eb7e9"),
                            CategoryId = new Guid("0c5f8f9e-a0e5-4698-87af-588da11adc6f"),
                            Color = "mint green",
                            CreatedDateEntity = new DateTime(2019, 12, 29, 18, 26, 12, 226, DateTimeKind.Local).AddTicks(866),
                            DriveType = 3,
                            EngineId = new Guid("351047a6-b4a0-465c-9c91-ac7f355f5535"),
                            GearBox = 2,
                            IsDeleted = false,
                            Manufacturer = "Cadillac",
                            Mileage = 122868,
                            Model = "Charger",
                            OriginCountry = "Mauritania",
                            PictureName = "Cadillac.jpg",
                            Type = 2,
                            UpdateDateEntity = new DateTime(2019, 12, 29, 18, 26, 12, 226, DateTimeKind.Local).AddTicks(872),
                            VIN = "NUPDWRJ43ZGK26675"
                        },
                        new
                        {
                            Id = new Guid("bad00308-e501-4b57-9ade-fc32280fb760"),
                            AmountDoors = 5,
                            AmountSeats = 2,
                            CatalogId = new Guid("924cce38-da44-4b44-a9f5-430d3830debe"),
                            CategoryId = new Guid("0c5f8f9e-a0e5-4698-87af-588da11adc6f"),
                            Color = "pink",
                            CreatedDateEntity = new DateTime(2019, 12, 29, 18, 26, 12, 226, DateTimeKind.Local).AddTicks(955),
                            DriveType = 2,
                            EngineId = new Guid("d20657e6-cd52-4282-9018-2bd17587119f"),
                            GearBox = 0,
                            IsDeleted = false,
                            Manufacturer = "Volkswagen",
                            Mileage = 178369,
                            Model = "Aventador",
                            OriginCountry = "Jersey",
                            PictureName = "Volkswagen.jpg",
                            Type = 3,
                            UpdateDateEntity = new DateTime(2019, 12, 29, 18, 26, 12, 226, DateTimeKind.Local).AddTicks(960),
                            VIN = "ULH7NOIMBWSW22924"
                        },
                        new
                        {
                            Id = new Guid("3726127e-1d00-4fd4-a26a-6cfdd0dfa583"),
                            AmountDoors = 5,
                            AmountSeats = 2,
                            CatalogId = new Guid("924cce38-da44-4b44-a9f5-430d3830debe"),
                            CategoryId = new Guid("0c5f8f9e-a0e5-4698-87af-588da11adc6f"),
                            Color = "turquoise",
                            CreatedDateEntity = new DateTime(2019, 12, 29, 18, 26, 12, 226, DateTimeKind.Local).AddTicks(1035),
                            DriveType = 3,
                            EngineId = new Guid("67a68076-9eaf-40cc-bc13-b410a8943f5b"),
                            GearBox = 3,
                            IsDeleted = false,
                            Manufacturer = "Fiat",
                            Mileage = 101601,
                            Model = "Element",
                            OriginCountry = "Marshall Islands",
                            PictureName = "Fiat.jpg",
                            Type = 4,
                            UpdateDateEntity = new DateTime(2019, 12, 29, 18, 26, 12, 226, DateTimeKind.Local).AddTicks(1039),
                            VIN = "9PCLXX4PEFYU79572"
                        },
                        new
                        {
                            Id = new Guid("3dbd4535-6b39-426f-98ea-9184a5073389"),
                            AmountDoors = 5,
                            AmountSeats = 4,
                            CatalogId = new Guid("26c28d0b-55b8-4f7a-92c3-a775565eb7e9"),
                            CategoryId = new Guid("0c5f8f9e-a0e5-4698-87af-588da11adc6f"),
                            Color = "cyan",
                            CreatedDateEntity = new DateTime(2019, 12, 29, 18, 26, 12, 226, DateTimeKind.Local).AddTicks(1113),
                            DriveType = 2,
                            EngineId = new Guid("3d4a562f-e3aa-4e57-be86-83460d977b60"),
                            GearBox = 1,
                            IsDeleted = false,
                            Manufacturer = "Mercedes Benz",
                            Mileage = 117456,
                            Model = "Grand Caravan",
                            OriginCountry = "Guatemala",
                            PictureName = "Mercedes Benz.jpg",
                            Type = 2,
                            UpdateDateEntity = new DateTime(2019, 12, 29, 18, 26, 12, 226, DateTimeKind.Local).AddTicks(1118),
                            VIN = "UJV5M6N8S0C756117"
                        },
                        new
                        {
                            Id = new Guid("f74e2894-0c87-45b4-ace5-dd901b59b3b7"),
                            AmountDoors = 3,
                            AmountSeats = 3,
                            CatalogId = new Guid("924cce38-da44-4b44-a9f5-430d3830debe"),
                            CategoryId = new Guid("055536e6-8d75-43ad-869f-5a77b6fa7ce7"),
                            Color = "plum",
                            CreatedDateEntity = new DateTime(2019, 12, 29, 18, 26, 12, 226, DateTimeKind.Local).AddTicks(1235),
                            DriveType = 0,
                            EngineId = new Guid("3d4a562f-e3aa-4e57-be86-83460d977b60"),
                            GearBox = 0,
                            IsDeleted = false,
                            Manufacturer = "Honda",
                            Mileage = 186932,
                            Model = "Mustang",
                            OriginCountry = "Chile",
                            PictureName = "Honda.jpg",
                            Type = 4,
                            UpdateDateEntity = new DateTime(2019, 12, 29, 18, 26, 12, 226, DateTimeKind.Local).AddTicks(1241),
                            VIN = "Z1AW3FRXUSCI15828"
                        },
                        new
                        {
                            Id = new Guid("f6198b7b-474d-4085-9720-d6ee45476a9d"),
                            AmountDoors = 2,
                            AmountSeats = 5,
                            CatalogId = new Guid("924cce38-da44-4b44-a9f5-430d3830debe"),
                            CategoryId = new Guid("8411e08f-c1d9-4a7c-a3c8-5c7f956645f3"),
                            Color = "tan",
                            CreatedDateEntity = new DateTime(2019, 12, 29, 18, 26, 12, 226, DateTimeKind.Local).AddTicks(1318),
                            DriveType = 3,
                            EngineId = new Guid("7176d110-4d14-4290-935c-3140156114e0"),
                            GearBox = 2,
                            IsDeleted = false,
                            Manufacturer = "Cadillac",
                            Mileage = 41601,
                            Model = "Element",
                            OriginCountry = "Christmas Island",
                            PictureName = "Cadillac.jpg",
                            Type = 3,
                            UpdateDateEntity = new DateTime(2019, 12, 29, 18, 26, 12, 226, DateTimeKind.Local).AddTicks(1323),
                            VIN = "1LDZNQH73NPV20732"
                        },
                        new
                        {
                            Id = new Guid("f90db5c9-dfe6-433d-8f46-4dac1a116320"),
                            AmountDoors = 2,
                            AmountSeats = 3,
                            CatalogId = new Guid("26c28d0b-55b8-4f7a-92c3-a775565eb7e9"),
                            CategoryId = new Guid("8411e08f-c1d9-4a7c-a3c8-5c7f956645f3"),
                            Color = "salmon",
                            CreatedDateEntity = new DateTime(2019, 12, 29, 18, 26, 12, 226, DateTimeKind.Local).AddTicks(1394),
                            DriveType = 0,
                            EngineId = new Guid("c0f13571-ef04-4bca-bc9a-c237b451e57b"),
                            GearBox = 1,
                            IsDeleted = false,
                            Manufacturer = "Nissan",
                            Mileage = 159458,
                            Model = "Camaro",
                            OriginCountry = "Belarus",
                            PictureName = "Nissan.jpg",
                            Type = 4,
                            UpdateDateEntity = new DateTime(2019, 12, 29, 18, 26, 12, 226, DateTimeKind.Local).AddTicks(1399),
                            VIN = "0JXOMIA13AV938634"
                        },
                        new
                        {
                            Id = new Guid("d6b00a88-04a0-4d0a-add7-67384725b297"),
                            AmountDoors = 2,
                            AmountSeats = 5,
                            CatalogId = new Guid("924cce38-da44-4b44-a9f5-430d3830debe"),
                            CategoryId = new Guid("0c5f8f9e-a0e5-4698-87af-588da11adc6f"),
                            Color = "yellow",
                            CreatedDateEntity = new DateTime(2019, 12, 29, 18, 26, 12, 226, DateTimeKind.Local).AddTicks(1474),
                            DriveType = 1,
                            EngineId = new Guid("c0f13571-ef04-4bca-bc9a-c237b451e57b"),
                            GearBox = 1,
                            IsDeleted = false,
                            Manufacturer = "Mini",
                            Mileage = 34290,
                            Model = "Alpine",
                            OriginCountry = "Mexico",
                            PictureName = "Mini.jpg",
                            Type = 1,
                            UpdateDateEntity = new DateTime(2019, 12, 29, 18, 26, 12, 226, DateTimeKind.Local).AddTicks(1479),
                            VIN = "N6A7D4RGRMUD51042"
                        },
                        new
                        {
                            Id = new Guid("b69e8023-6e38-4a80-a2f0-9f989e27212a"),
                            AmountDoors = 4,
                            AmountSeats = 4,
                            CatalogId = new Guid("924cce38-da44-4b44-a9f5-430d3830debe"),
                            CategoryId = new Guid("055536e6-8d75-43ad-869f-5a77b6fa7ce7"),
                            Color = "fuchsia",
                            CreatedDateEntity = new DateTime(2019, 12, 29, 18, 26, 12, 226, DateTimeKind.Local).AddTicks(1573),
                            DriveType = 3,
                            EngineId = new Guid("c7d9f487-1848-421b-8ce6-2cfdd1036c56"),
                            GearBox = 1,
                            IsDeleted = false,
                            Manufacturer = "Mini",
                            Mileage = 17324,
                            Model = "Mustang",
                            OriginCountry = "Nepal",
                            PictureName = "Mini.jpg",
                            Type = 4,
                            UpdateDateEntity = new DateTime(2019, 12, 29, 18, 26, 12, 226, DateTimeKind.Local).AddTicks(1578),
                            VIN = "YUEXVWVEYJJA54410"
                        },
                        new
                        {
                            Id = new Guid("20dde053-ef4f-46ca-81ce-d7c83a6b8a35"),
                            AmountDoors = 2,
                            AmountSeats = 4,
                            CatalogId = new Guid("924cce38-da44-4b44-a9f5-430d3830debe"),
                            CategoryId = new Guid("0c5f8f9e-a0e5-4698-87af-588da11adc6f"),
                            Color = "azure",
                            CreatedDateEntity = new DateTime(2019, 12, 29, 18, 26, 12, 226, DateTimeKind.Local).AddTicks(1650),
                            DriveType = 1,
                            EngineId = new Guid("7176d110-4d14-4290-935c-3140156114e0"),
                            GearBox = 2,
                            IsDeleted = false,
                            Manufacturer = "Nissan",
                            Mileage = 65897,
                            Model = "Silverado",
                            OriginCountry = "Svalbard & Jan Mayen Islands",
                            PictureName = "Nissan.jpg",
                            Type = 5,
                            UpdateDateEntity = new DateTime(2019, 12, 29, 18, 26, 12, 226, DateTimeKind.Local).AddTicks(1655),
                            VIN = "YE5HV67YLDCC43174"
                        },
                        new
                        {
                            Id = new Guid("137929da-8c3e-497d-8368-21ac4a4d8ab6"),
                            AmountDoors = 5,
                            AmountSeats = 5,
                            CatalogId = new Guid("26c28d0b-55b8-4f7a-92c3-a775565eb7e9"),
                            CategoryId = new Guid("0c5f8f9e-a0e5-4698-87af-588da11adc6f"),
                            Color = "cyan",
                            CreatedDateEntity = new DateTime(2019, 12, 29, 18, 26, 12, 226, DateTimeKind.Local).AddTicks(1773),
                            DriveType = 3,
                            EngineId = new Guid("3d4a562f-e3aa-4e57-be86-83460d977b60"),
                            GearBox = 0,
                            IsDeleted = false,
                            Manufacturer = "Hyandai",
                            Mileage = 85507,
                            Model = "Cruze",
                            OriginCountry = "Czech Republic",
                            PictureName = "Hyandai.jpg",
                            Type = 3,
                            UpdateDateEntity = new DateTime(2019, 12, 29, 18, 26, 12, 226, DateTimeKind.Local).AddTicks(1778),
                            VIN = "KIDWP5Q7GFNF58556"
                        },
                        new
                        {
                            Id = new Guid("3ffa8abf-7821-4029-845d-f176363b3a21"),
                            AmountDoors = 5,
                            AmountSeats = 5,
                            CatalogId = new Guid("26c28d0b-55b8-4f7a-92c3-a775565eb7e9"),
                            CategoryId = new Guid("8411e08f-c1d9-4a7c-a3c8-5c7f956645f3"),
                            Color = "silver",
                            CreatedDateEntity = new DateTime(2019, 12, 29, 18, 26, 12, 226, DateTimeKind.Local).AddTicks(1850),
                            DriveType = 2,
                            EngineId = new Guid("c0f13571-ef04-4bca-bc9a-c237b451e57b"),
                            GearBox = 1,
                            IsDeleted = false,
                            Manufacturer = "Rolls Royce",
                            Mileage = 1022,
                            Model = "Escalade",
                            OriginCountry = "Mozambique",
                            PictureName = "Rolls Royce.jpg",
                            Type = 1,
                            UpdateDateEntity = new DateTime(2019, 12, 29, 18, 26, 12, 226, DateTimeKind.Local).AddTicks(1856),
                            VIN = "XYPGA5EOHVZK97087"
                        },
                        new
                        {
                            Id = new Guid("44d7e912-c5ef-4e99-b2c9-e4e3bf198115"),
                            AmountDoors = 4,
                            AmountSeats = 5,
                            CatalogId = new Guid("26c28d0b-55b8-4f7a-92c3-a775565eb7e9"),
                            CategoryId = new Guid("0c5f8f9e-a0e5-4698-87af-588da11adc6f"),
                            Color = "tan",
                            CreatedDateEntity = new DateTime(2019, 12, 29, 18, 26, 12, 226, DateTimeKind.Local).AddTicks(1927),
                            DriveType = 3,
                            EngineId = new Guid("527d76bd-0892-4041-8008-172319ea0f0c"),
                            GearBox = 3,
                            IsDeleted = false,
                            Manufacturer = "Porsche",
                            Mileage = 110986,
                            Model = "Colorado",
                            OriginCountry = "Canada",
                            PictureName = "Porsche.jpg",
                            Type = 4,
                            UpdateDateEntity = new DateTime(2019, 12, 29, 18, 26, 12, 226, DateTimeKind.Local).AddTicks(1932),
                            VIN = "N55X038BI5NF94705"
                        },
                        new
                        {
                            Id = new Guid("beee2a82-be1e-49dc-975b-187f79b1b032"),
                            AmountDoors = 2,
                            AmountSeats = 4,
                            CatalogId = new Guid("26c28d0b-55b8-4f7a-92c3-a775565eb7e9"),
                            CategoryId = new Guid("055536e6-8d75-43ad-869f-5a77b6fa7ce7"),
                            Color = "violet",
                            CreatedDateEntity = new DateTime(2019, 12, 29, 18, 26, 12, 226, DateTimeKind.Local).AddTicks(2000),
                            DriveType = 0,
                            EngineId = new Guid("7176d110-4d14-4290-935c-3140156114e0"),
                            GearBox = 2,
                            IsDeleted = false,
                            Manufacturer = "Chevrolet",
                            Mileage = 33660,
                            Model = "Land Cruiser",
                            OriginCountry = "Romania",
                            PictureName = "Chevrolet.jpg",
                            Type = 0,
                            UpdateDateEntity = new DateTime(2019, 12, 29, 18, 26, 12, 226, DateTimeKind.Local).AddTicks(2005),
                            VIN = "FHX8TWRS33K139540"
                        },
                        new
                        {
                            Id = new Guid("51673933-e413-47e8-9daf-4adea58eb3eb"),
                            AmountDoors = 3,
                            AmountSeats = 3,
                            CatalogId = new Guid("26c28d0b-55b8-4f7a-92c3-a775565eb7e9"),
                            CategoryId = new Guid("055536e6-8d75-43ad-869f-5a77b6fa7ce7"),
                            Color = "maroon",
                            CreatedDateEntity = new DateTime(2019, 12, 29, 18, 26, 12, 226, DateTimeKind.Local).AddTicks(2077),
                            DriveType = 1,
                            EngineId = new Guid("e238cfff-9c27-4a9a-ac24-31f153a0e2ea"),
                            GearBox = 1,
                            IsDeleted = false,
                            Manufacturer = "Chrysler",
                            Mileage = 14009,
                            Model = "Impala",
                            OriginCountry = "Mauritania",
                            PictureName = "Chrysler.jpg",
                            Type = 3,
                            UpdateDateEntity = new DateTime(2019, 12, 29, 18, 26, 12, 226, DateTimeKind.Local).AddTicks(2082),
                            VIN = "CH3F3K6U02ZP50425"
                        },
                        new
                        {
                            Id = new Guid("a9d8bf87-5f71-4b3a-b76a-383694835550"),
                            AmountDoors = 3,
                            AmountSeats = 3,
                            CatalogId = new Guid("26c28d0b-55b8-4f7a-92c3-a775565eb7e9"),
                            CategoryId = new Guid("0c5f8f9e-a0e5-4698-87af-588da11adc6f"),
                            Color = "maroon",
                            CreatedDateEntity = new DateTime(2019, 12, 29, 18, 26, 12, 226, DateTimeKind.Local).AddTicks(2198),
                            DriveType = 2,
                            EngineId = new Guid("3d6a58b8-eb54-4a93-8b24-12777408ebe7"),
                            GearBox = 2,
                            IsDeleted = false,
                            Manufacturer = "Ford",
                            Mileage = 193304,
                            Model = "Jetta",
                            OriginCountry = "Holy See (Vatican City State)",
                            PictureName = "Ford.jpg",
                            Type = 2,
                            UpdateDateEntity = new DateTime(2019, 12, 29, 18, 26, 12, 226, DateTimeKind.Local).AddTicks(2204),
                            VIN = "DATO5QZ4RZKK76293"
                        },
                        new
                        {
                            Id = new Guid("ba0a232f-b684-4b9e-a0f2-7539537770e2"),
                            AmountDoors = 3,
                            AmountSeats = 5,
                            CatalogId = new Guid("924cce38-da44-4b44-a9f5-430d3830debe"),
                            CategoryId = new Guid("0c5f8f9e-a0e5-4698-87af-588da11adc6f"),
                            Color = "olive",
                            CreatedDateEntity = new DateTime(2019, 12, 29, 18, 26, 12, 226, DateTimeKind.Local).AddTicks(2282),
                            DriveType = 3,
                            EngineId = new Guid("67a68076-9eaf-40cc-bc13-b410a8943f5b"),
                            GearBox = 1,
                            IsDeleted = false,
                            Manufacturer = "Rolls Royce",
                            Mileage = 84665,
                            Model = "PT Cruiser",
                            OriginCountry = "Dominican Republic",
                            PictureName = "Rolls Royce.jpg",
                            Type = 1,
                            UpdateDateEntity = new DateTime(2019, 12, 29, 18, 26, 12, 226, DateTimeKind.Local).AddTicks(2287),
                            VIN = "SAPU5P00PTNP20976"
                        });
                });

            modelBuilder.Entity("CarCatalog.Database.Entities.Catalog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedDateEntity")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdateDateEntity")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Catalog");

                    b.HasData(
                        new
                        {
                            Id = new Guid("924cce38-da44-4b44-a9f5-430d3830debe"),
                            CreatedDate = new DateTime(2019, 12, 28, 20, 54, 31, 341, DateTimeKind.Local).AddTicks(7931),
                            CreatedDateEntity = new DateTime(2019, 12, 29, 18, 26, 12, 201, DateTimeKind.Local).AddTicks(1935),
                            IsDeleted = false,
                            Name = "animi",
                            UpdateDateEntity = new DateTime(2019, 12, 29, 18, 26, 12, 201, DateTimeKind.Local).AddTicks(1992),
                            UserId = new Guid("2fecd99a-e554-4b66-be26-026e12c3529e")
                        },
                        new
                        {
                            Id = new Guid("26c28d0b-55b8-4f7a-92c3-a775565eb7e9"),
                            CreatedDate = new DateTime(2019, 12, 29, 10, 29, 34, 54, DateTimeKind.Local).AddTicks(3276),
                            CreatedDateEntity = new DateTime(2019, 12, 29, 18, 26, 12, 203, DateTimeKind.Local).AddTicks(2207),
                            IsDeleted = false,
                            Name = "ut",
                            UpdateDateEntity = new DateTime(2019, 12, 29, 18, 26, 12, 203, DateTimeKind.Local).AddTicks(2231),
                            UserId = new Guid("9b1abdb4-8ef4-4544-bd06-9e0fe16c6bd8")
                        });
                });

            modelBuilder.Entity("CarCatalog.Database.Entities.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDateEntity")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PictureName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdateDateEntity")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Category");

                    b.HasData(
                        new
                        {
                            Id = new Guid("0c5f8f9e-a0e5-4698-87af-588da11adc6f"),
                            CreatedDateEntity = new DateTime(2019, 12, 29, 18, 26, 12, 204, DateTimeKind.Local).AddTicks(9684),
                            IsDeleted = false,
                            Name = "Sport",
                            PictureName = "Sport.jpg",
                            UpdateDateEntity = new DateTime(2019, 12, 29, 18, 26, 12, 204, DateTimeKind.Local).AddTicks(9717)
                        },
                        new
                        {
                            Id = new Guid("055536e6-8d75-43ad-869f-5a77b6fa7ce7"),
                            CreatedDateEntity = new DateTime(2019, 12, 29, 18, 26, 12, 205, DateTimeKind.Local).AddTicks(840),
                            IsDeleted = false,
                            Name = "Limousine",
                            PictureName = "Limousine.jpg",
                            UpdateDateEntity = new DateTime(2019, 12, 29, 18, 26, 12, 205, DateTimeKind.Local).AddTicks(854)
                        },
                        new
                        {
                            Id = new Guid("8411e08f-c1d9-4a7c-a3c8-5c7f956645f3"),
                            CreatedDateEntity = new DateTime(2019, 12, 29, 18, 26, 12, 205, DateTimeKind.Local).AddTicks(877),
                            IsDeleted = false,
                            Name = "Passenger",
                            PictureName = "Passenger.jpg",
                            UpdateDateEntity = new DateTime(2019, 12, 29, 18, 26, 12, 205, DateTimeKind.Local).AddTicks(880)
                        });
                });

            modelBuilder.Entity("CarCatalog.Database.Entities.Engine", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AmountCylinders")
                        .HasColumnType("int");

                    b.Property<float>("Capacity")
                        .HasColumnType("real");

                    b.Property<string>("Code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDateEntity")
                        .HasColumnType("datetime2");

                    b.Property<int>("Fuel")
                        .HasColumnType("int");

                    b.Property<int>("HorsePower")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("KiloWat")
                        .HasColumnType("int");

                    b.Property<bool>("Turbo")
                        .HasColumnType("bit");

                    b.Property<DateTime>("UpdateDateEntity")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Engine");

                    b.HasData(
                        new
                        {
                            Id = new Guid("3d4a562f-e3aa-4e57-be86-83460d977b60"),
                            AmountCylinders = 3,
                            Capacity = 1f,
                            Code = "25",
                            CreatedDateEntity = new DateTime(2019, 12, 29, 18, 26, 12, 206, DateTimeKind.Local).AddTicks(3751),
                            Fuel = 0,
                            HorsePower = 95,
                            IsDeleted = false,
                            KiloWat = 70,
                            Turbo = true,
                            UpdateDateEntity = new DateTime(2019, 12, 29, 18, 26, 12, 206, DateTimeKind.Local).AddTicks(3776)
                        },
                        new
                        {
                            Id = new Guid("b68f0932-74aa-4960-b84b-563c657132bd"),
                            AmountCylinders = 3,
                            Capacity = 1f,
                            Code = "30",
                            CreatedDateEntity = new DateTime(2019, 12, 29, 18, 26, 12, 206, DateTimeKind.Local).AddTicks(8002),
                            Fuel = 0,
                            HorsePower = 116,
                            IsDeleted = false,
                            KiloWat = 85,
                            Turbo = true,
                            UpdateDateEntity = new DateTime(2019, 12, 29, 18, 26, 12, 206, DateTimeKind.Local).AddTicks(8018)
                        },
                        new
                        {
                            Id = new Guid("da41b3e5-2727-41a9-8504-db2155424a26"),
                            AmountCylinders = 4,
                            Capacity = 1.5f,
                            Code = "35",
                            CreatedDateEntity = new DateTime(2019, 12, 29, 18, 26, 12, 206, DateTimeKind.Local).AddTicks(8099),
                            Fuel = 0,
                            HorsePower = 150,
                            IsDeleted = false,
                            KiloWat = 110,
                            Turbo = true,
                            UpdateDateEntity = new DateTime(2019, 12, 29, 18, 26, 12, 206, DateTimeKind.Local).AddTicks(8103)
                        },
                        new
                        {
                            Id = new Guid("527d76bd-0892-4041-8008-172319ea0f0c"),
                            AmountCylinders = 4,
                            Capacity = 2f,
                            Code = "40",
                            CreatedDateEntity = new DateTime(2019, 12, 29, 18, 26, 12, 206, DateTimeKind.Local).AddTicks(8109),
                            Fuel = 0,
                            HorsePower = 200,
                            IsDeleted = false,
                            KiloWat = 147,
                            Turbo = true,
                            UpdateDateEntity = new DateTime(2019, 12, 29, 18, 26, 12, 206, DateTimeKind.Local).AddTicks(8112)
                        },
                        new
                        {
                            Id = new Guid("3d6a58b8-eb54-4a93-8b24-12777408ebe7"),
                            AmountCylinders = 4,
                            Capacity = 1.4f,
                            Code = "A34",
                            CreatedDateEntity = new DateTime(2019, 12, 29, 18, 26, 12, 206, DateTimeKind.Local).AddTicks(8117),
                            Fuel = 0,
                            HorsePower = 204,
                            IsDeleted = false,
                            KiloWat = 150,
                            Turbo = true,
                            UpdateDateEntity = new DateTime(2019, 12, 29, 18, 26, 12, 206, DateTimeKind.Local).AddTicks(8120)
                        },
                        new
                        {
                            Id = new Guid("4f5b62c0-5346-4745-990a-8dc0a6688d80"),
                            AmountCylinders = 4,
                            Capacity = 2f,
                            Code = "40",
                            CreatedDateEntity = new DateTime(2019, 12, 29, 18, 26, 12, 206, DateTimeKind.Local).AddTicks(8138),
                            Fuel = 0,
                            HorsePower = 300,
                            IsDeleted = false,
                            KiloWat = 221,
                            Turbo = true,
                            UpdateDateEntity = new DateTime(2019, 12, 29, 18, 26, 12, 206, DateTimeKind.Local).AddTicks(8141)
                        },
                        new
                        {
                            Id = new Guid("68643845-0733-4bee-870b-1581b1db9470"),
                            AmountCylinders = 5,
                            Capacity = 2.5f,
                            Code = "45",
                            CreatedDateEntity = new DateTime(2019, 12, 29, 18, 26, 12, 206, DateTimeKind.Local).AddTicks(8146),
                            Fuel = 0,
                            HorsePower = 400,
                            IsDeleted = false,
                            KiloWat = 294,
                            Turbo = true,
                            UpdateDateEntity = new DateTime(2019, 12, 29, 18, 26, 12, 206, DateTimeKind.Local).AddTicks(8149)
                        },
                        new
                        {
                            Id = new Guid("c7d9f487-1848-421b-8ce6-2cfdd1036c56"),
                            AmountCylinders = 4,
                            Capacity = 2f,
                            Code = "35",
                            CreatedDateEntity = new DateTime(2019, 12, 29, 18, 26, 12, 206, DateTimeKind.Local).AddTicks(8287),
                            Fuel = 0,
                            HorsePower = 150,
                            IsDeleted = false,
                            KiloWat = 110,
                            Turbo = true,
                            UpdateDateEntity = new DateTime(2019, 12, 29, 18, 26, 12, 206, DateTimeKind.Local).AddTicks(8291)
                        },
                        new
                        {
                            Id = new Guid("8b43a35b-d306-404c-8e8c-78bef3ceb895"),
                            AmountCylinders = 4,
                            Capacity = 2f,
                            Code = "40",
                            CreatedDateEntity = new DateTime(2019, 12, 29, 18, 26, 12, 206, DateTimeKind.Local).AddTicks(8295),
                            Fuel = 0,
                            HorsePower = 190,
                            IsDeleted = false,
                            KiloWat = 140,
                            Turbo = true,
                            UpdateDateEntity = new DateTime(2019, 12, 29, 18, 26, 12, 206, DateTimeKind.Local).AddTicks(8298)
                        },
                        new
                        {
                            Id = new Guid("351047a6-b4a0-465c-9c91-ac7f355f5535"),
                            AmountCylinders = 4,
                            Capacity = 2f,
                            Code = "45",
                            CreatedDateEntity = new DateTime(2019, 12, 29, 18, 26, 12, 206, DateTimeKind.Local).AddTicks(8304),
                            Fuel = 0,
                            HorsePower = 245,
                            IsDeleted = false,
                            KiloWat = 180,
                            Turbo = true,
                            UpdateDateEntity = new DateTime(2019, 12, 29, 18, 26, 12, 206, DateTimeKind.Local).AddTicks(8307)
                        },
                        new
                        {
                            Id = new Guid("67a68076-9eaf-40cc-bc13-b410a8943f5b"),
                            AmountCylinders = 6,
                            Capacity = 3f,
                            Code = "50",
                            CreatedDateEntity = new DateTime(2019, 12, 29, 18, 26, 12, 206, DateTimeKind.Local).AddTicks(8311),
                            Fuel = 0,
                            HorsePower = 354,
                            IsDeleted = false,
                            KiloWat = 260,
                            Turbo = true,
                            UpdateDateEntity = new DateTime(2019, 12, 29, 18, 26, 12, 206, DateTimeKind.Local).AddTicks(8314)
                        },
                        new
                        {
                            Id = new Guid("e02e815d-c82d-45c2-848f-cd257334dc63"),
                            AmountCylinders = 6,
                            Capacity = 2.9f,
                            Code = "F50",
                            CreatedDateEntity = new DateTime(2019, 12, 29, 18, 26, 12, 206, DateTimeKind.Local).AddTicks(8319),
                            Fuel = 0,
                            HorsePower = 450,
                            IsDeleted = false,
                            KiloWat = 331,
                            Turbo = true,
                            UpdateDateEntity = new DateTime(2019, 12, 29, 18, 26, 12, 206, DateTimeKind.Local).AddTicks(8322)
                        },
                        new
                        {
                            Id = new Guid("e238cfff-9c27-4a9a-ac24-31f153a0e2ea"),
                            AmountCylinders = 6,
                            Capacity = 3f,
                            Code = "55",
                            CreatedDateEntity = new DateTime(2019, 12, 29, 18, 26, 12, 206, DateTimeKind.Local).AddTicks(8326),
                            Fuel = 0,
                            HorsePower = 340,
                            IsDeleted = false,
                            KiloWat = 250,
                            Turbo = true,
                            UpdateDateEntity = new DateTime(2019, 12, 29, 18, 26, 12, 206, DateTimeKind.Local).AddTicks(8329)
                        },
                        new
                        {
                            Id = new Guid("4707a2db-5c6c-4689-8b13-7d1244e7b3a4"),
                            AmountCylinders = 4,
                            Capacity = 2f,
                            Code = "35",
                            CreatedDateEntity = new DateTime(2019, 12, 29, 18, 26, 12, 206, DateTimeKind.Local).AddTicks(8336),
                            Fuel = 1,
                            HorsePower = 150,
                            IsDeleted = false,
                            KiloWat = 110,
                            Turbo = true,
                            UpdateDateEntity = new DateTime(2019, 12, 29, 18, 26, 12, 206, DateTimeKind.Local).AddTicks(8339)
                        },
                        new
                        {
                            Id = new Guid("c0f13571-ef04-4bca-bc9a-c237b451e57b"),
                            AmountCylinders = 4,
                            Capacity = 2f,
                            Code = "40",
                            CreatedDateEntity = new DateTime(2019, 12, 29, 18, 26, 12, 206, DateTimeKind.Local).AddTicks(8343),
                            Fuel = 1,
                            HorsePower = 190,
                            IsDeleted = false,
                            KiloWat = 140,
                            Turbo = true,
                            UpdateDateEntity = new DateTime(2019, 12, 29, 18, 26, 12, 206, DateTimeKind.Local).AddTicks(8346)
                        },
                        new
                        {
                            Id = new Guid("9e2e8a06-6932-4eaf-a502-d6dd8bbbf005"),
                            AmountCylinders = 4,
                            Capacity = 2f,
                            Code = "40",
                            CreatedDateEntity = new DateTime(2019, 12, 29, 18, 26, 12, 206, DateTimeKind.Local).AddTicks(8351),
                            Fuel = 1,
                            HorsePower = 204,
                            IsDeleted = false,
                            KiloWat = 150,
                            Turbo = true,
                            UpdateDateEntity = new DateTime(2019, 12, 29, 18, 26, 12, 206, DateTimeKind.Local).AddTicks(8354)
                        },
                        new
                        {
                            Id = new Guid("7176d110-4d14-4290-935c-3140156114e0"),
                            AmountCylinders = 6,
                            Capacity = 3f,
                            Code = "50",
                            CreatedDateEntity = new DateTime(2019, 12, 29, 18, 26, 12, 206, DateTimeKind.Local).AddTicks(8358),
                            Fuel = 1,
                            HorsePower = 347,
                            IsDeleted = false,
                            KiloWat = 255,
                            Turbo = true,
                            UpdateDateEntity = new DateTime(2019, 12, 29, 18, 26, 12, 206, DateTimeKind.Local).AddTicks(8361)
                        },
                        new
                        {
                            Id = new Guid("d20657e6-cd52-4282-9018-2bd17587119f"),
                            AmountCylinders = 6,
                            Capacity = 3f,
                            Code = "50",
                            CreatedDateEntity = new DateTime(2019, 12, 29, 18, 26, 12, 206, DateTimeKind.Local).AddTicks(8367),
                            Fuel = 1,
                            HorsePower = 286,
                            IsDeleted = false,
                            KiloWat = 210,
                            Turbo = true,
                            UpdateDateEntity = new DateTime(2019, 12, 29, 18, 26, 12, 206, DateTimeKind.Local).AddTicks(8370)
                        },
                        new
                        {
                            Id = new Guid("1451ebb5-443d-4da3-91a6-c15052a64550"),
                            AmountCylinders = 6,
                            Capacity = 3f,
                            Code = "45",
                            CreatedDateEntity = new DateTime(2019, 12, 29, 18, 26, 12, 206, DateTimeKind.Local).AddTicks(8374),
                            Fuel = 1,
                            HorsePower = 231,
                            IsDeleted = false,
                            KiloWat = 170,
                            Turbo = true,
                            UpdateDateEntity = new DateTime(2019, 12, 29, 18, 26, 12, 206, DateTimeKind.Local).AddTicks(8377)
                        });
                });

            modelBuilder.Entity("CarCatalog.Database.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Avatar")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDateEntity")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdateDateEntity")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("User");

                    b.HasData(
                        new
                        {
                            Id = new Guid("2fecd99a-e554-4b66-be26-026e12c3529e"),
                            Avatar = "https://s3.amazonaws.com/uifaces/faces/twitter/jarjan/128.jpg",
                            CreatedDateEntity = new DateTime(2019, 12, 29, 18, 26, 12, 166, DateTimeKind.Local).AddTicks(8467),
                            IsDeleted = false,
                            Name = "Noah.Roberts56",
                            UpdateDateEntity = new DateTime(2019, 12, 29, 18, 26, 12, 169, DateTimeKind.Local).AddTicks(3052)
                        },
                        new
                        {
                            Id = new Guid("e213f3f3-72a9-4da0-9b94-a85651ee05af"),
                            Avatar = "https://s3.amazonaws.com/uifaces/faces/twitter/her_ruu/128.jpg",
                            CreatedDateEntity = new DateTime(2019, 12, 29, 18, 26, 12, 188, DateTimeKind.Local).AddTicks(1703),
                            IsDeleted = false,
                            Name = "Luigi53",
                            UpdateDateEntity = new DateTime(2019, 12, 29, 18, 26, 12, 188, DateTimeKind.Local).AddTicks(1758)
                        },
                        new
                        {
                            Id = new Guid("17b29634-451f-4106-9c3f-3d959a29bc53"),
                            Avatar = "https://s3.amazonaws.com/uifaces/faces/twitter/pmeissner/128.jpg",
                            CreatedDateEntity = new DateTime(2019, 12, 29, 18, 26, 12, 188, DateTimeKind.Local).AddTicks(2235),
                            IsDeleted = false,
                            Name = "Taya73",
                            UpdateDateEntity = new DateTime(2019, 12, 29, 18, 26, 12, 188, DateTimeKind.Local).AddTicks(2243)
                        },
                        new
                        {
                            Id = new Guid("9b1abdb4-8ef4-4544-bd06-9e0fe16c6bd8"),
                            Avatar = "https://s3.amazonaws.com/uifaces/faces/twitter/andytlaw/128.jpg",
                            CreatedDateEntity = new DateTime(2019, 12, 29, 18, 26, 12, 188, DateTimeKind.Local).AddTicks(2402),
                            IsDeleted = false,
                            Name = "Emil14",
                            UpdateDateEntity = new DateTime(2019, 12, 29, 18, 26, 12, 188, DateTimeKind.Local).AddTicks(2408)
                        });
                });

            modelBuilder.Entity("CarCatalog.Database.Entities.Car", b =>
                {
                    b.HasOne("CarCatalog.Database.Entities.Catalog", "Catalog")
                        .WithMany("Cars")
                        .HasForeignKey("CatalogId");

                    b.HasOne("CarCatalog.Database.Entities.Category", "Category")
                        .WithMany("Cars")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CarCatalog.Database.Entities.Engine", "Engine")
                        .WithMany("Cars")
                        .HasForeignKey("EngineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CarCatalog.Database.Entities.Catalog", b =>
                {
                    b.HasOne("CarCatalog.Database.Entities.User", "User")
                        .WithMany("Catalogs")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
